spring:
  application:
    name: order-service-api
  datasource:
    url: jdbc:mysql://localhost:3306/order_db?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: update




server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka