spring:
  application:
    name: place-order-service-api
  datasource:
    url: jdbc:mysql://localhost:3306/placer-order_db?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: update

  config:
      import: "optional:configserver:http://localhost:8088"




